export const UPDATE_RECOMMENDATION_START = "UPDATE_RECOMMENDATION_START" 
export const UPDATE_RECOMMENDATION_SUCCESS = "UPDATE_RECOMMENDATION_SUCCESS" 
export const UPDATE_RECOMMENDATION_FAIL = "UPDATE_RECOMMENDATION_FAIL" 

export const SET_RATING_VALUE = "SET_RATING_VALUE"
export const SET_RATING_VALUE_FINISH = "SET_RATING_VALUE_FINISH"